geostyler/geostyler-openlayers-parser

data/olStyles/line_simpleline.ts
data/olStyles/point_simplepoint.ts
data/olStyles/point_styledlabel.ts
data/olStyles/polygon_transparentpolygon.ts
package.json
src/OlStyleParser.spec.ts
src/OlStyleParser.ts
src/Util/OlStyleUtil.ts

Introduces writeStyle implementation for basic support for OpenLayers Styles.

Introduce writeStyle implementation for basic support for OL Styles

---

src/OlStyleParser.ts

This adds the static title property.

Adds title property

---

package.json
src/Util/OlStyleUtil.ts
tsconfig.build.json

This updates the build and publish script to automate the test, build and publishing workflows.

Update the build/publish script

---

data/olStyles/line_simpleline.ts
data/styles/line_simpleline.ts
src/OlStyleParser.spec.ts
src/OlStyleParser.ts

Converts line dash properties in the read and write functions of the parser.

Convert line dash in read and write functions

---

src/OlStyleParser.ts

Title says it all.
Fixes broken parse functionality for `OlStyleText`

Set styleType to point for parsed text

---

data/styles/line_simpleline.ts
data/styles/multi_simplefillSimpleline.ts
data/styles/multi_simplelineLabel.ts
data/styles/multi_twoRulesSimplepoint.ts
data/styles/point_icon.ts
data/styles/point_simplecross.ts
data/styles/point_simplepoint.ts
data/styles/point_simplepoint_filter.ts
data/styles/point_simplesquare.ts
data/styles/point_simplestar.ts
data/styles/point_simpletriangle.ts
data/styles/point_simplex.ts
data/styles/point_styledlabel.ts
data/styles/polygon_transparentpolygon.ts
package.json
src/OlStyleParser.spec.ts
src/OlStyleParser.ts

**Important:** Please wait with merging this PR until
was merged.
Update code to changes in above mentioned PR. 
Also, rename functions where multiple symbolizers will be parsed. Update tests and testfiles accordingly.

Rename symbolizer to symbolizers

---

src/OlStyleParser.ts

Title explains it all...
resolves https://github.com/terrestris/geostyler-openlayers-parser/pull/19#issuecomment-414202844

Update code-docs for readStyle and writeStyle

---

src/OlStyleParser.ts

parse outlineWidth of FillSymbolizer

---

package.json

Push tags on release

---

package.json

Bump version of ol-util to latest version using OpenLayers 4

---

package.json

Introduces ol@4.6.5 and ol-util@0.5.0 as dev dependency

---

src/OlStyleParser.ts

Fixes the same issues as https://github.com/terrestris/geostyler/pull/646
@chrismayer @terrestris/devs Any thoughts are appreciated (we can discuss in https://github.com/terrestris/geostyler/pull/646)

Fix comparisons

---

package.json

fix(package): update @terrestris/ol-util to version 2.0.1

---

src/Util/OlStyleUtil.spec.ts
src/Util/OlStyleUtil.ts

Check if HEX color is valid and is not already an `rgba` color string

Checks of HEX color strings in OlStyleUtil

---

package.json
src/OlStyleParser.ts
src/Util/OlStyleUtil.ts

Only construct an `ol.style.Fill` in case a color is set.
@terrestris/devs Please review.

Fix handling of empty fills

---

package.json

fix(package): update @terrestris/ol-util to version 3.0.0

---

package-lock.json
package.json

This updates several dependencies.
closes #214
closes #216 
closes #217

Updates several packages

---

README.md

`geostyle` should be `pointSimplePoint` of JS fails

Fix browser example

---

package-lock.json
package.json

This updates several dependencies including `geostyler-style`.
closes #225 
closes #224 
closes #223 
closes #222 
closes #221 
closes #219

Updates several dependencies

---

src/OlStyleParser.ts

This updates the typing and adds some linting.

Enhancements to typing and linting

---

package-lock.json
package.json
src/OlStyleParser.ts
tsconfig-eslint.json
tsconfig.json

This updates geostyler-style to v3.
Closes #255

Updates geostyler-style to v3

---

data/styles/filter_invalidFilter.ts
data/styles/filter_nestedFilter.ts
data/styles/filter_simpleFilter.ts
data/styles/multi_twoRulesSimplepoint.ts
data/styles/point_simplecross.ts
data/styles/point_simplepoint.ts
data/styles/point_simplepoint_filter.ts
data/styles/point_simplesquare.ts
data/styles/point_simplestar.ts
data/styles/point_simpletriangle.ts
data/styles/point_simplex.ts
data/styles/scaleDenom_line_circle.ts
data/styles/scaleDenom_line_circle_overlap.ts
package-lock.json
package.json
src/OlStyleParser.ts

This updates geostyler-style 4.0.0 and ol 6.5.0 and adapts the affected code.

Updates geostyler-style and ol

---

browser-build.config.js
package-lock.json
package.json

This makes the browser build `es5` compatible and adds the browserslist that is also used in the geostyler main repository..

make browser build es5 compatible

---

package-lock.json
package.json

Updates the geostyler-style dependency.
https://github.com/geostyler/geostyler-style/pull/297

Update geostyler-style dependency

---

src/Util/OlStyleUtil.ts

Co-authored-by: Marc Jansen <jansen@terrestris.de>
Small follow up to https://github.com/geostyler/geostyler-openlayers-parser/pull/562.
@geostyler/devs Please review

docs: improve getHexCode docs

---

.github/FUNDING.yml
README.md

Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your contribution.
------------
Please give a short description of the changes you …

docs: add funding information

---

data/olStyles/function_case.ts
data/styles/function_case.ts
package-lock.json
package.json
src/OlStyleParser.spec.ts
src/OlStyleParser.ts
src/Util/OlStyleUtil.ts

This updates geostyler-style to v7.3.1 and ol to v7.4.0 and adds support for the new function expressions of the geostyler-style.

Add support for more geostyler-functions

---

README.md

Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your contribution.
------------
Please give a short description of the changes you …

docs: add code sprint 2025 announcement

---

README.md

Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your contribution.
------------
Please give a short description of the changes you …

docs: replace master with main on badges

---

data/olFlatStyles/filter_simpleFilter.ts
data/olFlatStyles/line_simpleline.ts
data/olFlatStyles/multi_twoRulesSimplepoint.ts
data/olFlatStyles/point_icon_simple.ts
data/olFlatStyles/point_simplepoint.ts
data/olFlatStyles/polygon_simple.ts
data/olFlatStyles/text_placement_line.ts
data/styles/point_icon_simple.ts
package-lock.json
package.json
src/OlFlatStyleParser.spec.ts
src/OlFlatStyleParser.ts
src/Util/OlFlatStyleUtil.spec.ts
src/Util/OlFlatStyleUtil.ts
src/Util/OlStyleUtil.ts

This adds support for openlayers flatstyles (see https://openlayers.org/en/latest/apidoc/module-ol_style_flat.html).

feat: add OlFlatStyleParser

---

jest.config.cjs

Collect coverage from all files and not just the files inside the `src` folder.
Also increase the coverage threshold to not have the CI fail on main.

chore: collect coverage from all source files
