src/OlStyleParser.spec.ts, src/OlStyleParser.ts, src/Util/OlStyleUtil.spec.ts, src/Util/OlStyleUtil.ts
This implements the ``readStyle`` function by adding a basic parser functionality to read OpenLayers Style objects. 
Supported Symbolizer Types: ``Point``, ``Line`` and ``Fill``.
=> Introduce readStyle implementation for basic support for OL Styles 

src/OlStyleParser.spec.ts, src/OlStyleParser.ts
Transforms the text for a label by a non-string attribute field to a string value. Transformation is done in the OpenLayers Style Function.
Related to https://github.com/terrestris/geostyler/issues/194.
=> Transform label value to string in OL-Style-Func

data/styles/point_simplepoint_filter.ts, data/styles/point_styledlabel.ts
Due to the new version 0.6.0 of [GeoStyler Style](https://github.com/terrestris/geostyler-style), this corrects all demo data for the unit tests.
=> Apply demo data for unit tests due to gs-style v0.6.0

.vscode/launch.json, data/olStyles/point_icon.ts, data/styles/point_icon.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This introduces the `getOlIconSymbolizerFromIconSymbolizer` method to be able to write `ol.style.Icon` from our `IconSymbolizer`.
It also includes the `launch.json` config to debug tests.
=> Introduces getOlIconSymbolizerFromIconSymbolizer

data/olStyles/multi_simplelineLabel.ts, data/olStyles/point_icon.ts, data/olStyles/point_simplecross.ts, data/olStyles/point_simplesquare.ts, data/olStyles/point_simplestar.ts, data/olStyles/point_simpletriangle.ts, data/olStyles/point_simplex.ts, data/styles/multi_simplefillSimpleline.ts, data/styles/multi_simplelineLabel.ts, data/styles/multi_twoRulesSimplepoint.ts, data/styles/point_icon.ts, data/styles/point_simplecross.ts, data/styles/point_simplepoint.ts, data/styles/point_simplepoint_filter.ts, data/styles/point_simplesquare.ts, data/styles/point_simplestar.ts, data/styles/point_simpletriangle.ts, data/styles/point_simplex.ts, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
**Important:** Please wait with merging this PR until
was merged.
Update parser to parse WellKnownNames. geostyler-openlayers-parser now is able to parse WellKnownNames according to definitions in above mentioned PR. 
Added tests and testfiles for every supported WellKnownName. Updated existing tests and testfiles to match new definitions.
=> WellKnownNames

data/olStyles/point_styledlabel.ts, data/styles/point_styledlabel.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
Note that geostyler-style TextSymbolizer halo will be parsed from/to Stroke property of ol.Style.Text.
=> Parse Halo and Rotation of TextSymbolizer

data/olStyles/point_simplebackslash.ts, data/olStyles/point_simplecarrow.ts, data/olStyles/point_simpledot.ts, data/olStyles/point_simplehorline.ts, data/olStyles/point_simpleoarrow.ts, data/olStyles/point_simpleplus.ts, data/olStyles/point_simpleslash.ts, data/olStyles/point_simpletimes.ts, data/olStyles/point_simplevertline.ts, data/styles/point_simplebackslash.ts, data/styles/point_simplecarrow.ts, data/styles/point_simpledot.ts, data/styles/point_simplehorline.ts, data/styles/point_simpleoarrow.ts, data/styles/point_simpleplus.ts, data/styles/point_simpleslash.ts, data/styles/point_simplesquare.ts, data/styles/point_simplestar.ts, data/styles/point_simpletimes.ts, data/styles/point_simpletriangle.ts, data/styles/point_simplevertline.ts, data/styles/point_simplex.ts, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
**Important:** Please wait with merging this PR until
was merged.
Now parsing additional WellKnownNames defined by geoserver. Updated parser to new geostyler-style definitions. Also added and updated tests and testfiles.
**Note:** So far, geostyler-openlayers-parser does not handle added WellKnownNames perfectly. Following problems and fallbacks exist:
*readStyle():*
- Cannot distinguish between `shape://carrow` and `shape://oarrow`. Fallback: `shape://carrow`
- Cannot distinguish between `Circle` and `shape://dot`. Fallback: `Circle`
- Cannot distinguish between `Cross` and `shape://plus`. Fallback: `Cross`
- Cannot distinguish between `X` and `shape://times`. Fallback: `X`
*writeStyle():*
- Cannot write style for `shape://oarrow`. Fallback: use `shape://carrow` style
=> Parse geoserver-specific WellKnownNames

src/OlStyleParser.ts
For some symbols it is necessary to explicitly set a default stroke color. Otherwise they are not being rendered. This PR sets the default stroke color for newly added WellKnownSymbols.
=> Default stroke color for WellKnownSymbols

data/olStyles/point_styledLabel_static.ts, data/styles/multi_simplelineLabel.ts, data/styles/point_styledLabel_static.ts, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts, src/Util/OlStyleUtil.spec.ts, src/Util/OlStyleUtil.ts
**Important:** Please wait with merging this PR until
was merged.
With this PR it is possible to parse templates for TextSymbolizers. Simple text will be parsed as static text. Text in double curly braces ({{}}) will be interpreted as feature property. Combinations are possible.
If a template only contains simple text, an OpenLayers StyleText will be returned instead of an OlStyleFunction. This allows bidirectional parsing of those. If a template contains at least one set of double curly braces, an OlStyleFunction will be returned.
Also fixed parsing of fonts in TextSymbolizer.
Tests and testfiles were added/updated accordingly.
=> Parse TextSymbolizer template

src/OlStyleParser.ts
When using geostyler-openlayers-parser outside of the react universe, the application using openlayers-parser and openlayers-parser itself are running on distinct openlayers instances. This leads to unexpected behaviour and should be avoided.
@KaiVolland and I resolved this issue by allowing an optional argument `ol` to the constructor, which will overwrite the internally used openlayers instance. However, this does not look like an optimal solution.
We were also thinking about adding all needed openlayers objects explicitly in the constructor and not using an own instance within the parser, which would work for both the usual build and the browser build, but we would loose backwards compatibility. So we discarded this idea.
@marcjansen @dnlkoch @chrismayer do you have any ideas to solve …
=> "Fix" working with global variable ol in browser build

package.json
Updated geostyler-style version to v0.14.1 and downgraded a few other dependencies to fix the browser build.
=> Update geostyler-style & fix browser build

browser-build.config.js, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This PR should resolve [this issue](https://github.com/terrestris/geostyler/issues/463).
New type `OlParserStyleFct` was defined, which consists of an ol.StyleFct and an additional property `_geoStylerStyle`. This allows bidirectional parsing of openlayers styles. Function arguments and return values of `readStyle` and `writeStyle` were updated accordingly.
`readStyle` now accepts an olStyle, an OlStyle[ ] or an OlParserStyleFct. In case of the former two types a geostyler-style with a single rule and 1:n symbolizers will be returned. In case of an OlParserStyleFct the geostyler-style from property `__geoStylerStyle` will be returned without any changes.
`writeStyle` now always returns a OlParserStyleFct. This allows the direct use of the returned value within openlayers.
This PR also …
=> Apply new type OlParserStyleFct

data/styles/scaleDenom_line.ts, data/styles/scaleDenom_line_circle.ts, data/styles/scaleDenom_line_circle_overlap.ts, index.d.ts, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts, src/Util/OlStyleUtil.ts
**Important:** This PR builds upon open PR #39. So please wait with merging until the other one was merged.
geostyler-openlayers-parser is now able to parse scaleDenominator in `writeStyle`. OlParserStyleFct checks the current scale and returns only those styles where the current scale lies within specified scaleDenominator(s). 
MinScale is inclusive, MaxScale is exclusive.
resolves https://github.com/terrestris/geostyler/issues/462
=> Parse scale denominator

src/OlStyleParser.ts
instanceof check in `geoStylerStyleToOlParserStyleFct` failes if using another openLayers instance that was passed through constructor. Thus, replacing instanceof with a typeof check to increase robustness.
=> Replace instanceof with typeof check

data/styles/filter_invalidFilter.ts, data/styles/filter_nestedFilter.ts, data/styles/filter_simpleFilter.ts, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
Parser now also writes simple and nested filters. Added tests and jest:watch script to package.json to facilitate testing. 
Closes https://github.com/terrestris/geostyler/issues/461
=> Write filter & Add jest:watch

dev-build.config.js, package.json, src/OlStyleParser.ts, tsconfig.build.json, tsconfig.json
This adds a dev build that excludes OpenLayers. We should discuss if we want this for the prod build as well since we're building a library. See also https://webpack.js.org/guides/author-libraries/
@terrestris/devs Please review.
=> Add dev build excluding openlayers

src/OlStyleParser.ts
Since `0` is falsy, a zero opacity previously led to opaque color values in OpenLayers.
@terrestris/devs Please review.
=> Fixes handling of zero opacity

package-lock.json, package.json
This updates openlayers (`ol`) to version 6.
As `ol` is a peer dependency this should be a breaking change. --> Major release inc. 
It also fixes the import of the `@terrestris/ol-util` and does an `npm update`.
=> Updates openlayers to version 6

package.json
As the tags are already pushed by np the git push fails which results in not having the package.json pushed.
=> Updates the release script in the package.json

data/styles/multi_simplefillSimpleline.ts, src/OlStyleParser.ts
If no lineDash was defined in an openlayers `Stroke` it will be set to `null` by default. This leads to errors in the UI as defaultProps will not be used on `null` values. 
To have a consistent handling ol-parser checks now if lineDash is `null` and sets it to `undefined`.
=> Parse lineDash null as undefined

data/olStyles/point_fontglyph.ts, data/styles/point_fontglyph.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts, src/Util/OlStyleUtil.spec.ts, src/Util/OlStyleUtil.ts
This PR extends the parser logic to allow rendering mark symbolizers using font glyphs instead of built-in shapes (`Circle`, `Square`, `shape://...` etc.). This is done by specifying a WellKnownName property with the following syntax: `ttf://<font name>#<char hex code>`.
The change works both ways (Geostyler > OL and OL > Geostyler), the caveat being that if an OL style was created *without* using the parser and that it contains a text style meant for symbols, the parser will have no way of knowing that it is supposed to be a `MarkSymbolizer` and not a `TextSymbolizer`.
This is because when generating an OL style containing a font-based mark, the resulting text style will contain a dummy `geostyler-mark-symbolizer` font which does not impact rendering but lets the parser know that it is …
=> Support font-based mark symbolizers

data/olStyles/polygon_transparentpolygon.ts, data/styles/polygon_transparentpolygon.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
Currently the OL parser isn't (fully) supporting outlineOpacity and outlineDasharray in the Fill symbolizer. This PR aims to add support for this. It also likely fixes #229 and geostyler/geostyler#1222.
~Please let me know if this feature is of interest and if I'm on the right path with the implementation. I'll then add relevant tests. :-)~ 
Tests have now been added, thanks for the encouragement, @jansule!
Please note, I copy/pasted the template from the geostyler/geostyler repo. Maybe it would be good to have a template for this repo available too?
=> Add support for outlineOpacity and outlineDasharray in fill symbolizer

data/styles/point_dynamic_icon.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This PR allows deciding IconSymboilizers URL based on features attribute by supporting template literals. We can write `{{path}}` in symbolizer definition
```
symbolizers: [{
kind: 'Icon',
image: '{{path}}',
}]
``` 
and it would then take the attribute `path` from each feature and generate the URL to load the icon from.
https://github.com/geostyler/geostyler-openlayers-parser/issues/363
=> Support dynamic attribute based point icons

src/OlStyleParser.ts
The features start to flicker due to a longstanding bug (https://github.com/openlayers/openlayers/issues/3137) in OpenLayers when using style function to set icon image and having more than 33 features. This PR fixes that problem by caching the styles using src URL as dictionary key.
This is a followup of https://github.com/geostyler/geostyler-openlayers-parser/pull/364 for issue https://github.com/geostyler/geostyler-openlayers-parser/issues/363
=> Cache dynamic icon styles to fix flickering

src/OlStyleParser.ts
This adds support for the `allowOverlap` property of the `TextSymbolizer`
This should give an answer to this old issue: https://github.com/geostyler/geostyler/issues/1207
=> Add support for allowOverlap in TextSymbolizer

src/OlStyleParser.ts
This adds the `unsupportedProperties` info object to clarify which parts of the GeoStyler Style are covered by the `geostyler-openlayers-parser`.
=> Add unsupportedProperties info object

babel.config.js, package-lock.json, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts, src/Util/OlStyleUtil.spec.ts, src/Util/OlStyleUtil.ts
This updates the parser to work with geostyler-style 5. As the ouput of `readStyle` and `writeStyle` change accordingly this is a **breaking-change** :exclamation: 
=> geostyler-style v 5

package-lock.json, package.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This removes the `@terrestris/ol-util` as it was only used to calculate the scale for resolution but increased the bundle (and node_modules) size. The corresponding code to calculate the code was just copied in place.
=> Remove @terrestris/ol-util

data/olStyles/polygon_simple.ts, data/olStyles/unsupported_properties.ts, data/styles/point_simplepoint_filter.ts, data/styles/point_styledlabel.ts, data/styles/polygon_simple.ts, data/styles/unsupported_properties.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This adds the `unsupportedProperties` to the `WriteStyleResult`.
It also fixes `getFillSymbolizerFromOlStyle` as it added unneed keys to the output.
=> Adds unsupportedProperties feedback to WriteStyleResult

src/OlStyleParser.ts
This fixes `checkForUnsupportedProperties`.
- [x ] Bugfix
=> Fixes `checkForUnsupportedProperties`

package-lock.json, package.json, src/OlStyleParser.ts, src/Util/OlStyleUtil.ts
This handles the geostyler-style expression type.
=> Update to geostyler-style 6.0.0

data/styles/point_icon.ts, package-lock.json, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This drops the support for `size` in the `IconSymbolizer` as it was handled very inconvenient which led to confusion:
https://github.com/geostyler/geostyler/issues/1746
https://github.com/geostyler/geostyler-openlayers-parser/issues/624
The upcoming ol release will include `width` and `height` for the `ol/style/Icon` so we will be able to implement it correctly with the next ol version:
https://github.com/openlayers/openlayers/pull/14364
=> Drop support for IconSymbolizer.size

src/OlStyleParser.ts
This removes `graphicFill` from the `unsupportedProperties` as it is supported since #388 
=> Remove `graphicFill` from unsupportedProperties

src/OlStyleParser.ts
Fixes the scale check for `null` values. Previously the scale check would lead to an out of scale determination if `max` or `min` was set to null.
@geostyler/devs Please review.
=> Fix scale check

src/Util/OlStyleUtil.spec.ts, src/Util/OlStyleUtil.ts
A MapServer class such as in the tests [here](https://github.com/geostyler/geostyler-mapfile-parser/blob/17c74e1001802891c840c66729f0807a4dfbc412/data/mapfiles/point_st_sample_style_tags_single_filter_list.map#L12) :
```
CLASS
EXPRESSION {bus,bank}
```
Converts to the following GeoStyler style (see [here](https://github.com/geostyler/geostyler-mapfile-parser/blob/17c74e1001802891c840c66729f0807a4dfbc412/data/styles/point_st_sample_style_tags_single_filter_list.ts#L12)):
```
filter: [
'==', {
name: 'strMatches',
args: [{
name: 'property',
args: ['name']
}, '/(bus|bank)/']
```
When this is converted to an OpenLayers style function using the code in [OlStyleUtil](https://github.com/geostyler/geostyler-openlayers-parser/blob/27a47d211a149272b06e45d4a9ee4dde4aff6726/src/Util/OlStyleUtil.ts#L352 …
=> Handle RegEx with flags

.github/workflows/on-pull-request.yml, .github/workflows/on-push-master.yml, package.json
See https://github.com/orgs/geostyler/discussions/2181
Strangely I also had to update the target Node.js version during CI and the versions of the used actions, otherwise typescript would err out. Locally, I failed to `npm i` on Node.js 14, btw.
Please review.
=> Add funding field to package.json

src/OlStyleParser.ts
Add support for the symbolizer vibility field. Simply does not create a style if visibility is false.
https://github.com/geostyler/geostyler/issues/1940
https://github.com/geostyler/geostyler/pull/2155
=> feat: support symbolizer visibility

jest.config.js, jest/Environment.js, src/OlStyleParser.ts
This PR makes use of `structuredClone` when writing the style to avoid manipulation of the input object.
It also pushes `null` to the styles array when the `visibilty` of a `symbolizer` is set to `false`. 
Fixes #740 
=> Clone style to avoid manipulation

data/styles/polygon_transparentpolygon.ts, data/styles/unsupported_properties.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This fixes the handling of the opacity of the fill color in a `FillSymbolizer`. As per `geostyler-style` this information should be stored in [`fillOpacity`](https://github.com/geostyler/geostyler-style/blob/master/style.ts#L220) and not in [`opacity`](https://github.com/geostyler/geostyler-style/blob/master/style.ts#L138) as this is an overall opacity of the whole symbolizer.
This also ensures to be in sync with other parsers like the SLDParser.
=> Use `fillOpacity` instead of `opacity` for `FillSymbolizer`

data/olStyles/text_placement_line.ts, data/olStyles/text_placement_point.ts, data/styles/text_palcement_line_center.ts, data/styles/text_placement_line.ts, data/styles/text_placement_point.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts, src/Util/OlStyleUtil.ts
This adds support for parsing placement of TextSymbolizer. 
This also adds a NP check for 
Depends on: https://github.com/geostyler/geostyler-style/pull/584
=> Text placement

data/styles/filter_comparison_propertyFunction.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
Fixes a bug when both arguments to a comparison filter are property functions. The parser would extract the property from the feature and then use the value as a key for the feature again. e.g. feature.get(feature.get('x'));
#791 
=> fix: parsing of property functions in filter args

src/OlStyleParser.ts
Bug fix for scope declared variables in geoStylerFilterToOlParserFilter method
Thank you for considering giving code and/or documentation back to this project, you're awesome and we appreciate your work.
Please review the [guidelines for contributing](https://github.com/geostyler/geostyler/blob/master/CONTRIBUTING.md) and the [code of conduct](https://github.com/geostyler/geostyler/blob/master/CODE_OF_CONDUCT.md) of this repository. This makes it easy for you to give back and for us to accept your changes.
Please use the template below the line for the pull request description, and make sure to tick off the boxes in the checklists. In your final pull request everything above the next horizontal line can be removed to not distract reviewers or other readers.
Again: thank you for your …
=> Update OlStyleParser.ts fixing issue 795

data/olStyles/point_simpleoffset.ts, data/styles/point_simpleoffset.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
Check if offset is an array instead of number as it's always an array of numbers. By checking for array the offset will be in the openlayers style as displacement.
https://github.com/geostyler/geostyler-openlayers-parser/issues/799
=> bugfix: check if Array instead of number

data/olStyles/unsupported_properties.ts, data/styles/unsupported_properties.ts, src/OlStyleParser.spec.ts, src/OlStyleParser.ts
This MR enhances the test for unsupported properties.
=> Enhance unsupported properties test

package-lock.json, package.json
Bumps geostyler-style to its latest version `10.0.0`.
none
=> chore(deps): bump geostyler-style to 10.0.0

data/olFlatStyles/filter_nestedFilter.ts, src/OlFlatStyleParser.spec.ts, src/Util/OlFlatStyleUtil.spec.ts, src/Util/OlFlatStyleUtil.ts
This improves parsing expressions in FlatRule filters. In addition to filter expressions, common expressions are now also being parsed. Also, if the first argument of a comparison filter is a 'get' expression, we directly extract the propertyName.
None
=> fix(OlFlatStyleParser): properly parse expressions in FlatRule filters

.github/workflows/on-pull-request.yml, .github/workflows/on-push-main.yml, .github/workflows/on-push-master.yml
This PR makes it so that:
* the workflows running for PRs and the `main` branch now use `bun` instead of NPM
* the workflow intended to run for `main` was still targeting the `master` branch
=> Use bun in CI workflows

data/olFlatStyles/point_opaquepoint.ts, data/styles/point_opaquepoint.ts, src/OlFlatStyleParser.spec.ts, src/OlFlatStyleParser.ts
This sets the geostyler fillOpacity property for MarkSymbolizers instead of opacity.
None
=> fix(OlFlatStyleParser): set fillOpacity on circle styles
